// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BlogEditorController from "./blog_editor_controller"
application.register("blog-editor", BlogEditorController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import CommentEditController from "./comment_edit_controller"
application.register("comment-edit", CommentEditController)

import DarkmodeController from "./darkmode_controller"
application.register("darkmode", DarkmodeController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ReadMoreController from "./read_more_controller"
application.register("read-more", ReadMoreController)
